### ISSUE TITLE
Curated list of Haskell packages

### ISSUE THREAD

**Issue by Tehnix** [haskell-lang/haskell-lang#12] opened 2016-04-27 23:27 UTC
First off, great initiative! Hopefully this can replace haskell.org instead of competing with it, but I'll leave that for another discussion.

---

From what I could gather about the project, one of the goals was to make the website a stop for newcomers where they could navigate how to learn Haskell.

One of my major gripes as someone a bit inexperienced still, but following the community closely, is that I often have a hard time finding out what the recommended packages are for certain things.

There are efforts such as [http://haskelliseasy.readthedocs.io](http://haskelliseasy.readthedocs.io) that try to offer a more opinionated list of packages for various purposes, and I think this would be something that a Haskell site could benefit from - either by linking to the aforementioned site, or by supplying a list itself.

If this is a bit off scope with the project or goals of the project, feel free to close the issue. Just thought I'd add what I've found hard to navigate in my own experience.

**Comment by bitemyapp** [comment] 2016-04-28 00:06
I think it'd be better to leave it on haskelliseasy.com. Part of the point of the site is being based on personal experience or testing I've done with a beginner.

I don't include anything just because somebody asked me to. I don't think it's possible for a committee or group of people to reproduce that selectivity.

I'd call this out of scope for now, but if people are interested in digging into this problem and why I made haskelliseasy.com, I'd be willing to discuss it.

I'd have explained the decisions/exclusions/inclusions more but doing that usually makes people angry and at that point I'm basically doing work for free so that people can yell at me on the internet more.

**Comment by zimurgh** [comment] 2016-04-28 01:30
@bitemyapp I'd be interested in learning more of the subtle decisions that lead to the content that is currently presented on the site.

**Comment by snoyberg** [comment] 2016-04-28 05:45
We may be able to break this up into two tiers:
1. Packages that are almost universally agreed to and ubiquitous: bytestring, text, vector, containers
2. Much more opinionated packages: conduit vs pipes, CSV or XML parsing libraries, etc. I'd say providing links to websites like haskelliseasy (or hosting opinionated pages on haskell-lang.org) could be appropriate.

Reasoning: let's share common resources that have no real dispute, and make it easy for people to educate themselves on more controversial issues easily.

**Comment by Tehnix** [comment] 2016-04-28 10:49
@snoyberg I think that actually sounds like a great way to handle it.

**Comment by snoyberg** [comment] 2016-05-04 18:16
An initial version of this is now available at: http://ci.haskell-lang.org/packages

I think this issue may be safe to close now, with further additions handled via PRs to https://github.com/haskell-lang/haskell-lang/edit/master/config/package-info.yaml. Any objection?

**Comment by chrisdone** [comment] 2016-05-05 08:14
Merging into #27.

**Closed as completed by chrisdone** 2016-05-05 08:14 UTC
